version: '3.4'

networks:
  dev:
   driver: bridge

services:
  znoapp:
    image: docker.io/library/znoapp
    depends_on:
      - "app_db"
    container_name: znoapp-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DbConnection=User ID=postgres;Password=qwerty;Server=app_db;Port=5432;Database=SampleDbZno; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=SampleDbZno
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:	  